version: "3.8"
services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"


# docker-compose.yml
# version: "3.8"
# services:
#   mongo:
#     image: mongo:5.0
#     container_name: mongo
#     environment:
#         - MONGO_INITDB_ROOT_USERNAME=root
#         - MONGO_INITDB_ROOT_PASSWORD=password
#     restart: unless-stopped
#     ports:
#       - "27017:27017"
#     volumes:
#       - ./database/db:/data/db
#       - ./database/dev.archive:/Databases/dev.archive
#       - ./database/production:/Databases/production
#   mongo-express:
#     image: mongo-express
#     container_name: mexpress
#     environment:
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#       - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
#       - ME_CONFIG_BASICAUTH_USERNAME=mexpress
#       - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
#     depends_on:
#       - mongo
#     command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]
#     restart: unless-stopped
#     ports:
#       - "8081:8081"
#     links:
#       - mongo
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8081"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#       start_period: 30s

# For linux run this command "chmod +x wait-for-it.sh"

# FROM mongo-express
# COPY wait-for-it.sh /node_modules/mongo-express/wait-for-it.sh
# RUN chmod +x /node_modules/mongo-express/wait-for-it.sh
