version: '3'
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app:ro #bind mount volumn
      - /app/node_modules #annonymous volume
    environment:
      - NODE_ENV=development
    command: npm run dev