name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    # - run: npm run dev

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Copy repository to server
      run: |
          SERVER_PATH=/var/www/github-action/node-express-mongodb-boilerplate

          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -v sct@$192.168.1.59 "cd $SERVER_PATH && git pull"
