name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    # - run: npm run dev

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Copy repository to server
      # run: |
      #   echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #   chmod 600 ~/.ssh/id_rsa
      #   ssh -o StrictHostKeyChecking=no sct@192.168.1.59
      #   ssh -v sct@192.168.1.59 "cd /var/www/github-action/node-express-mongodb-boilerplate && git pull
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          SSH_OPTIONS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          
          SERVER_USER=sct
          SERVER_IP=192.168.1.59
          SERVER_PATH=/var/www/github-action/node-express-mongodb-boilerplate

          # Connect to the server
          ssh -v $SSH_OPTIONS $SERVER_USER@$SERVER_IP "cd $SERVER_PATH && git pull origin"
