name: Deploy to Local Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Upload to the Linux server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Debug SSH_PRIVATE_KEY
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to local server
      run: |
        ssh sct@192.168.1.59 "cd /var/www/github-action/node-express-mongodb-boilerplate && git pull"
