name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    # - run: npm run dev

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        run: |
          SERVER_USER=secrets.SSH_PRIVATE_KEY
          SERVER_IP=192.168.1.59
          SERVER_PATH=/var/www/github-action/node-express-mongodb-boilerplate

          # SSH configuration options
          SSH_OPTIONS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

          # Connect to the server and pull the latest changes
          ssh $SSH_OPTIONS $SERVER_USER@$SERVER_IP "cd $SERVER_PATH && git pull origin main"
          